version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  app:
    image: nequi-app:latest
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: jdbc:postgresql://db:5432/mydb
        DB_USERNAME: user
        DB_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - mynetwork
volumes:
  db_data:

networks:
  mynetwork:
