server:
  port: 8080
spring:
  webflux:
    base-path: /api
  profiles:
    active: local
  application:
    name: nequi-test
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:validate}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  health:
    redis:
      enabled: false
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
